#version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: sio-postgres
    environment:
      POSTGRES_USER: sio_user
      POSTGRES_PASSWORD: sio_password
      POSTGRES_DB: sio_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: sio-backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: sio_user
      DB_PASS: sio_password
      DB_NAME: sio_db
      JWT_SECRET: "chiave_segreta_super_sicura_per_il_corso_segretissimissima"
    depends_on:
      - db
    restart: always

  frontend:
    build: ./sio-frontend
    container_name: sio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Interfaccia web di Prometheus (debug)

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # Grafana sar√† su localhost:3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password login iniziale
    depends_on:
      - prometheus
volumes:
  pg_data:
